### ISSUE TITLE
Interrupted animations cause end element to disappear

### ISSUE THREAD

**Issue by chrislgrigg** [mx-albert/compose-shared-elements#2]
Hey Albert! I'm running into an issue where elements will disappear if their transitions are interrupted. I haven't put together a demo repo yet but you could reproduce it pretty easily:

**TLDR**: Create a simple view that has a shared element that animates slowly between three positions. Add a button to toggle the state from 1 -> 2 -> 3 -> repeat. Click to start an animation and then click again to interrupt it. You'll see that it never makes it to the updated target position; instead, it just disappears completely.

I think the expected behavior would be for it to snap to its end position when interrupted. If this was the case, interrupting the transition from position 1 to 2 should make it snap to 2 and then animate there to position 3.

### My troubleshooting attempt

I spent a little time trying to fix this in the code but I haven't found a good workaround. It looks like the root of the issue is that [this coroutine](https://github.com/mxalbert1996/compose-shared-elements/blob/main/shared-elements/src/main/java/com/mxalbert/sharedelements/SharedElementsRoot.kt#L110-L121) calls `transition.onTransitionFinished()` on whichever transition started first -- it never gets called for the second one. So in my example above, if I interrupt the transition from 1->2, the completion of transition 3 will call `onTransitionFinished()` on transition2 instead of transition3. This then doesn't unhide the correct element [here](https://github.com/mxalbert1996/compose-shared-elements/blob/main/shared-elements/src/main/java/com/mxalbert/sharedelements/SharedElementsRoot.kt#L45-L47).

A possible start of a fix might involve tracking the active animation. I found that I could get my code to correctly identify when the wrong element was called in `onTransitionFinished()` by adding `val activeAnimations = mutableMapOf<Any, Any>()` to `SharedElementsRootState`, where the key is the element key and value is the active animating screenKey, and then setting it during `onElementDisposed()` (the start of the next animation) and checking it during `onTransitionFinished()`. Something like this...

```kotlin
    fun onElementDisposed(elementInfo: SharedElementInfo) {
        activeAnimations.put(elementInfo.key, elementInfo.screenKey)
        choreographer.postCallback(elementInfo) {
            val tracker = getTracker(elementInfo)
            tracker.onElementUnregistered(elementInfo)
            if (tracker.isEmpty) trackers.remove(elementInfo.key)
        }
    }

@Composable
private fun SharedElementTransitionsOverlay(rootState: SharedElementsRootState) {
  // unchanged...
                scope.launch {
                   // unchanged...
                    activeScreenKey = rootState.activeAnimations.get(startElement.info.key)
                    val correctTarget = activeScreenKey == startElement.info.screenKey
                    Timber.tag("wtf").i("firing onTransitionFinished() for startElement ${startElement.info.screenKey}. Is this correct? $correctTarget")
                    transition.onTransitionFinished()
                }
}
```

But I haven't figured out what to do with this information, everything I've tried breaks it in a new way.

I'd really appreciate your help with this, it breaks my interface in some ways that are complete show-stoppers. Thank you for all your work!

**Comment by mxalbert1996** [comment]
I will look into this but generally you should prevent screen change during transition as shown in the demo [here](https://github.com/mxalbert1996/compose-shared-elements/blob/654088f8baa1c57073cde54d58c003b85dbde025/demo/src/main/java/com/mxalbert/sharedelements/demo/MainActivity.kt#L168).

**Comment by chrislgrigg** [comment]
I’d like to but it’s not possible due to some of the requirements for my
interface.

You could maybe look into taking advantage of the `CancellationException`
thrown when `animateTo` is interrupted. It doesn’t seem to be thrown in
this case, the coroutine never seems to be interrupted (that seems to be
part of the problem) but maybe you could find a way to make an early state
change trigger a cancellation which then does some sort of cleanup as a
side-effect?

Wish I could help more but I didn’t have time to piece together how the
whole thing works. I really appreciate your work and help!
